### ISSUE TITLE
Pin of servos

### ISSUE THREAD

**Issue by CanonDieCamera** [Lichtwerkstatt/XRTL_Hardware#20]
The wiki says that one of the pins for the servo is 26. I wanted to put an LED on the connection for servo 1 and therefore used pin 26. After that didn't work, I checked the circuit board diagrams and saw that according to them, pins 33 and 25 are for the servos and pins 26 and 27 are for the relays. However, since there is no entry about the relays, I am not sure whether this is an error or not.

Btw. using pin 33 for the LED worked fine.

**Comment by FalkoFuroro** [comment]
It's now corrected! Thanks
